# file: C:\Users\erena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\xdist\looponfail.py
# hypothesis_version: 6.140.2

[1.0, 2.0, '#', '# MODIFIED', '--looponfail', '-f', '.', '.__path_hook__', '.py', '.pyc', 'Any', 'ERROR', 'LOOPONFAILING', 'RemoteControl:', 'channel', 'closing', 'execnet.Channel', 'exiting', 'gateway', 'looponfail', 'looponfailroots', 'received', 'reprcrash', 'sending', 'store_true', 'usepdb', 'w', 'waiting for changes', 'xdist']